export const Slideritems = [
    {
        id:1,
        img:"https://img.tatacliq.com/images/i7/437Wx649H/MP000000010632204_437Wx649H_202109171909051.jpeg",
        title:"IPhones",
        desc: `Supercharged for pro's 
                exchange bonus of ₹5000*`,
        bg: "#6acceb",
    },
    {
        id:2,
        img:"https://www.zdnet.com/a/img/resize/b40babe27312cb8e8d305c0bd230a382a3c06eff/2020/11/16/37e33024-2892-4bb7-9d21-6ac6f7544def/apple-macbook-pro-m1-2020-5.jpg?auto=webp&height=900&width=1200",
        title:"MacBook Pro",
        desc: `Make the move
                to Mac`,
        bg: "#94baf7",
    },
    {
        id:3,
        img:"https://5.imimg.com/data5/VV/CT/JI/SELLER-78323498/voltas-split-ac-500x500.jpg",
        title:"Air Conditioner",
        desc: `Price drop on ACs 
                from ₹20200*`,
        bg: "#bfffab",
    },
    {
        id:4,
        img:"https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1631806739-sony-x90j-1631806723.jpg?crop=1xw:1xh;center,top&resize=480:*",
        title:"SONY Bravia XR",
        desc: `World's 1st TVs With Cognitive Intelligence`,
        bg: "#f5ffa1",
    },
];

export const categories = [
    {
      id: 1,
      img: "https://rukminim2.flixcart.com/image/800/960/kqgyhe80/cargo/7/q/i/s-men21-cargo-black-red-tape-maniac-original-imag4h8zu8wwugjn.jpeg?q=50",
      title: "Cool Cargos",
      Moreinfo: "30% off",
      cat: "Men",
    },
    {
      id: 2,
      img: "https://rukminim2.flixcart.com/image/800/960/k3ncakw0pkrrdj/top/w/d/y/xxl-mt204-oomph-original-imafmjdwnbhgufff.jpeg?q=50",
      title: "Women's Tops",
      Moreinfo: "Extra 10% off",
      cat: "Women",
    },
    {
      id: 3,
      img: "https://5.imimg.com/data5/HI/GC/MY-35426765/mix-dry-fruits-500x500.jpg",
      title: "Dry Fruits",
      Moreinfo: "Starting from ₹99",
      cat: "Dry Fruits",
    },
    {
        id: 4,
        img: "https://www.sony-asia.com/image/74a4284c46882245b5a1b640432f94b3?fmt=pjpeg&wid=660&bgcolor=F1F5F9&bgc=F1F5F9",
        title: "Headphones",
        Moreinfo: "Starting from ₹999",
        cat: "Electronics",
      },
      {
        id: 5,
        img: "https://n4.sdlcdn.com/imgs/i/b/f/puma-bags-Multi-Color-Polyester-SDL186282683-1-cf653.jpg",
        title: "Laptop Bags",
        Moreinfo: "From ₹999 + 20% off",
        cat: "Accessory",
      },
  ];

  export const popularProducts = [
    {
      id:1,
      img:"https://assets.myntassets.com/h_1440,q_100,w_1080/v1/assets/images/2181012/2018/9/14/9d9956c4-ae0d-483d-b61d-fdd2da47f3321536929289500-Roadster-Women-Tshirts-9581536929288548-1.jpg",
    },
    {
      id:2,
      img:"https://rukminim2.flixcart.com/image/714/857/jdajwy80/watch/9/p/e/ng9463al06-fastrack-original-imaf289k5yz2bd2x.jpeg?q=50",
    },
    {
      id:3,
      img:"https://staticimg.titan.co.in/Titan/Catalog/2486SM01_1.jpg?pView=pdp",
    },
    {
      id:4,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR09BMNiHAdcgFJ2m-tyaJ-ttXM0gjSSqGhDg&usqp=CAU",
    },
    {
      id:5,
      img:"https://m.media-amazon.com/images/I/61Eh8J69jJL._MCnd_AC_UL320_.jpg",
    },
    {
      id:6,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK0v63uEWq80KL8DmOls8JGyC3ktIOhZJXXw&usqp=CAU",
    },
    {
      id:7,
      img:"https://m.media-amazon.com/images/I/51R4FJdgbMS._SL1500_.jpg",
    },
    {
      id:8,
      img:"https://assets.myntassets.com/dpr_1.5,q_60,w_400,c_limit,fl_progressive/assets/images/7687197/2018/11/6/d2fb226e-91d6-45b3-8d2e-77e3c17568171541503070806-Athena-Women-Coats-5511541503070658-1.jpg",
    },
    {
        id:9,
        img : "https://m.media-amazon.com/images/I/81vDZyJQ-4L._SL1500_.jpg",
    },
    {
        id: 10,
        img: "https://www.findmygsm.com/wp-content/uploads/2021/10/Xiaomi-Mi-10-Pro-5G-1-500x500-1.jpg",
    },
  ]

  export const Kurtas = [
    {
        id:1,
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sMEJjJ93L8yNYhE8IjECW3e0-jODoy4DdQ&usqp=CAU",
        title:"LIBAS",
        desc: "Gulmohar Women Printed - Kurta",
        color: "Dark Blue",
        price : "₹657",
        basePrice : "₹1057",
        offer : "46% Off",
    },
    {
        id:2,
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStlYxIAmj_g1hWUiFnDuUQK015RZSj8snykFD-f_FR3pc1naO9oLCreuvUcFSQmB0Sp-Y&usqp=CAU",
        title:"W",
        desc: "W - Women cotton - Kurta",
        color: "Light Pink",
        price : "₹677",
        basePrice : "₹800",
        offer : "16% Off",
    },
    {
        id:3,
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdpH6iiblMhT9x6JG4Q7iCcbjyPopLgUyzvA&usqp=CAU",
        title:"LIBAS",
        desc: "Women Printed cotton - Kurta",
        color: "Pink",
        price : "₹597",
        basePrice : "₹957",
        offer : "32% Off",
    },
    {
        id:4,
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSda6olTzs8K3jdCNCDcy1nNc7e-ecgI14Dzg&usqp=CAU",
        title:"Allen Solly",
        desc: "Women Casual cotton - Kurta",
        color: "Brown",
        price : "₹257",
        basePrice : "₹1057",
        offer : "76% Off",
    },
    {
      id:5,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-FqthkDZhzsMw4vRrHEcrlQJrb2Iioh6kCFpY7T3Dg8rd-iGMPYfbzpDuwpOfgybr7Os&usqp=CAU",
      title:"Allen Solly",
      desc: "Women Printed cotton - Kurta",
      color: "Yellow",
      price : "₹1657",
      basePrice : "₹2057",
      offer : "56% Off",
  },
  {
      id:6,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-bKagT0HQ6P08kEWo_fYm1ebjknVlYY8Fap64vp83GTddfJcPL5bFOF2AzaOQInmdUNU&usqp=CAU",
      title:"BIBA",
      desc: "Women's Ariba fashion - Kurta",
      color: "Orange - Blue",
      price : "₹2657",
      basePrice : "₹3057",
      offer : "10% Off",
  },
  {
      id:7,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2cz9gUwnYRK5SK90gBaSPNhF1WGL2XAqoSQ&usqp=CAU",
      title:"LIBAS",
      desc: "Karagre Women's - Kurta",
      color: "Sandal-Color",
      price : "₹357",
      basePrice : "₹1057",
      offer : "69% Off",
  },
  {
      id:8,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA3BWxyhHv06s44LI_F_wh6gmNIMI0s3wPFA&usqp=CAU",
      title:"Allen Solly",
      desc: "Women Printed cotton - Kurta",
      color: "Pink",
      price : "₹900",
      basePrice : "₹1057",
      offer : "6% Off",
  },
  {
    id:9,
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKcAWYKA3VXd_DdpmYmXutGSbH1yBOiH92cg&usqp=CAU",
    title:"LIBAS",
    desc: "Women Miskaat cotton - Kurta",
    color: "White - Blue",
    price : "₹500",
    basePrice : "₹1057",
    offer : "52% Off",
},
{
    id:10,
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk3MEMJo8gJOV7wljXjo0UY6qnvwc3Q8oGYQ&usqp=CAU",
    title:"BIBA",
    desc: "Women Printed cotton - Kurta",
    color: "Black",
    price : "₹799",
},
{
    id:11,
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9sUInK4luNDlDONGMdfzWC9FCxXAQsUKnZA&usqp=CAU",
    title:"LIBAS",
    desc: "Women Printed cotton - Kurta",
    color: "Gray",
    price : "₹957",
    basePrice : "₹1057",
    offer : "9% Off",
},
{
    id:12,
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRf7j7xsFJz1wbCopetMgevTYfTLhJPgq04dQ&usqp=CAU",
    title:"Allen Solly",
    desc: "Nypa Women Printed - Kurta",
    color: "Brown",
    price : "₹1500",
    basePrice : "₹999",
    offer : "36% Off + 5% Extra",
},
{
  id:13,
  img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCfQv9qR44OgiRZDOgcQ1JM7Rk5-6mM4z4Og&usqp=CAU",
  title:"LIBAS",
  desc: "Women Printed cotton - Kurta",
  color: "Green",
  price : "₹2001",
  basePrice : "₹2602",
  offer : "33% Off",
},
{
  id:14,
  img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmxaDnYzTa6kyLmko72H6lahQpgPR60VY0kA&usqp=CAU",
  title:"BIBA",
  desc: "Cradly Women's - Kurta",
  color: "White",
  price : "₹999",
  basePrice : "₹1599",
  offer : "49% Off",
},
{
  id:15,
  img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsDRy2XX8pj0IBKHwaFLLw_moz13IiwDqf6A&usqp=CAU",
  title:"LIBAS",
  desc: "Combo Women's cotton - Kurtas",
  color: "Black & pink",
  price : "₹657",
  basePrice : "₹1057",
  offer : "46% Off",
},
];
